In [98]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Convolution2D,MaxPooling2D,Flatten
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [99]:
train_datagen = ImageDataGenerator(rescale = 1./255, shear_range = 0.2, zoom_range = 0.2 , horizontal_flip = True)
test_datagen = ImageDataGenerator(rescale = 1./255)

In [100]:
x_train = train_datagen.flow_from_directory(r"E:\SmartInternz_Pynb\Image_for_ass6 data\trainset", target_size = (64,64), batch_size = 16, class_mode = "categorical")
x_test = test_datagen.flow_from_directory(r"E:\SmartInternz_Pynb\Image_for_ass6 data\testset", target_size = (64,64), batch_size = 16, class_mode = "categorical")

Found 70 images belonging to 10 classes.
Found 30 images belonging to 10 classes.


In [101]:
cnn = Sequential()

In [102]:
cnn.add(Convolution2D(32, (3, 3), input_shape= (64, 64, 3)))

In [103]:
cnn.add(MaxPooling2D((2,2)))

In [104]:
cnn.add(Flatten())

In [105]:
cnn.add(Dense(units = 120, kernel_initializer = "random_uniform", activation = "relu"))

In [106]:
cnn.add(Dense(units = 10, kernel_initializer = "random_uniform", activation = "softmax"))

In [107]:
cnn.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics = ["accuracy"])

In [108]:
cnn.fit_generator(x_train , steps_per_epoch = 70/16, epochs = 20, validation_data = x_test , validation_steps = 30/16)

Epoch 1/20
4/4 [==============================] - 9s 2s/step - loss: 3.3112 - accuracy: 0.0714 - val_loss: 2.5390 - val_accuracy: 0.0667
Epoch 2/20
4/4 [==============================] - 7s 2s/step - loss: 2.2349 - accuracy: 0.2857 - val_loss: 2.2166 - val_accuracy: 0.2000
Epoch 3/20
4/4 [==============================] - 7s 2s/step - loss: 1.9537 - accuracy: 0.2286 - val_loss: 2.3277 - val_accuracy: 0.2000
Epoch 4/20
4/4 [==============================] - 6s 1s/step - loss: 1.9150 - accuracy: 0.4000 - val_loss: 2.3359 - val_accuracy: 0.1000
Epoch 5/20
4/4 [==============================] - 6s 1s/step - loss: 1.6630 - accuracy: 0.4714 - val_loss: 2.3924 - val_accuracy: 0.1333
Epoch 6/20
4/4 [==============================] - 6s 2s/step - loss: 1.5239 - accuracy: 0.5429 - val_loss: 2.5549 - val_accuracy: 0.1000
Epoch 7/20
4/4 [==============================] - 7s 2s/step - loss: 1.4882 - accuracy: 0.4571 - val_loss: 2.5326 - val_accuracy: 0.2333
Epoch 8/20
4/4 [=========================

In [109]:
cnn.save("Image.h5")

In [110]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

In [111]:
mod=load_model("Image.h5")

In [112]:
img1 = image.load_img("cat1.jpg", target_size=(64,64))
img2 = image.load_img("elephant6.jpg", target_size=(64,64))
img3 = image.load_img("fish1.jpg", target_size=(64,64))
img4 = image.load_img("iguana1.jpg", target_size=(64,64))
img5 = image.load_img("lemur6.jpg", target_size=(64,64))

In [113]:
x1 = image.img_to_array(img1)
x2 = image.img_to_array(img2)
x3 = image.img_to_array(img3)
x4 = image.img_to_array(img4)
x5 = image.img_to_array(img5)

In [114]:
import numpy as np
x1 = np.expand_dims(x1, axis = 0)
x2 = np.expand_dims(x2, axis = 0)
x3 = np.expand_dims(x3, axis = 0)
x4 = np.expand_dims(x4, axis = 0)
x5 = np.expand_dims(x5, axis = 0)

In [115]:
cat = mod.predict(x1)
elephant = mod.predict(x2)
fish = mod.predict(x3)
iguana = mod.predict(x4)
lemur = mod.predict(x5)

In [116]:
cat[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [117]:
elephant[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [118]:
fish[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [119]:
iguana[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [120]:
lemur[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)

In [121]:
image = ["cat", "eagle", "eel", "elephant", "elk", "fish", "hen", "iguana", "lemur", "newt"]

In [122]:
cat = image[np.argmax(cat[0])]
cat

'cat'

In [123]:
elephant = image[np.argmax(elephant[0])]
elephant

'elephant'

In [124]:
fish = image[np.argmax(fish[0])]
fish

'fish'

In [125]:
iguana = image[np.argmax(iguana[0])]
iguana

'iguana'

In [126]:
lemur = image[np.argmax(lemur[0])]
lemur

'lemur'