In [1]:
import numpy as np
import pandas as pd
import sklearn.metrics as mse
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
ds = pd.read_csv(r"E:\SmartInternz_Pynb\50_Startups.csv")
ds

R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87              NaN  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08             NaN        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [3]:
ds.isnull().any()

R&D Spend          False
Administration      True
Marketing Spend     True
State              False
Profit             False
dtype: bool

In [4]:
ds.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [5]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   49 non-null     float64
 2   Marketing Spend  49 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [6]:
ds.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       49.000000        49.000000      50.000000
mean    73721.615600   121564.038163    212725.266735  112012.639200
std     45902.256482    28264.721000    122959.103760   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103057.490000    134050.070000   90138.902500
50%     73051.080000   122782.750000    214634.810000  107978.190000
75%    101602.800000   145077.580000    299737.290000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [7]:
ds["Administration"].fillna(ds["Administration"].mean(),inplace = True)
ds["Marketing Spend"].fillna(ds["Marketing Spend"].mean(),inplace = True)

In [8]:
ds.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [9]:
ds.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [10]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [11]:
x = ds.iloc[:,:-1].values
y = ds.iloc[:,4].values

In [12]:
x

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 212725.26673469393, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 121564.03816326526, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16

In [13]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [14]:
ct=ColumnTransformer([('one',OneHotEncoder(),[3])],remainder='passthrough')
x=ct.fit_transform(x)

In [15]:
ds["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [16]:
x

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 212725.26673469393],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 121564.03816326526, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 9

In [17]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [18]:
x_train.shape

(40, 6)

In [19]:
y_train.shape

(40,)

In [20]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [21]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
reg=Sequential()
reg.add(Dense(units=6,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))
reg.add(Dense(units=1,kernel_initializer= "random_uniform",activation= "relu"))
reg.compile(optimizer="rmsprop",loss="mean_squared_error")

In [22]:
reg.fit(x_train,y_train,epochs=500)

Epoch 1/500
2/2 [==============================] - 1s 0s/step - loss: 13615994880.0000
Epoch 2/500
2/2 [==============================] - 0s 4ms/step - loss: 13615994880.0000
Epoch 3/500
2/2 [==============================] - 0s 3ms/step - loss: 13615991808.0000
Epoch 4/500
2/2 [==============================] - 0s 4ms/step - loss: 13615991808.0000
Epoch 5/500
2/2 [==============================] - 0s 4ms/step - loss: 13615990784.0000
Epoch 6/500
2/2 [==============================] - 0s 4ms/step - loss: 13615989760.0000
Epoch 7/500
2/2 [==============================] - 0s 3ms/step - loss: 13615988736.0000
Epoch 8/500
2/2 [==============================] - 0s 4ms/step - loss: 13615988736.0000
Epoch 9/500
2/2 [==============================] - 0s 4ms/step - loss: 13615988736.0000
Epoch 10/500
2/2 [==============================] - 0s 3ms/step - loss: 13615986688.0000
Epoch 11/500
2/2 [==============================] - 0s 4ms/step - loss: 13615985664.0000
Epoch 12/500
2/2 [=============

2/2 [==============================] - 0s 5ms/step - loss: 13614527488.0000
Epoch 93/500
2/2 [==============================] - 0s 4ms/step - loss: 13614438400.0000
Epoch 94/500
2/2 [==============================] - 0s 3ms/step - loss: 13614356480.0000
Epoch 95/500
2/2 [==============================] - 0s 3ms/step - loss: 13614258176.0000
Epoch 96/500
2/2 [==============================] - 0s 4ms/step - loss: 13614150656.0000
Epoch 97/500
2/2 [==============================] - 0s 5ms/step - loss: 13614052352.0000
Epoch 98/500
2/2 [==============================] - 0s 4ms/step - loss: 13613945856.0000
Epoch 99/500
2/2 [==============================] - 0s 5ms/step - loss: 13613824000.0000
Epoch 100/500
2/2 [==============================] - 0s 5ms/step - loss: 13613701120.0000
Epoch 101/500
2/2 [==============================] - 0s 4ms/step - loss: 13613583360.0000
Epoch 102/500
2/2 [==============================] - 0s 4ms/step - loss: 13613452288.0000
Epoch 103/500
2/2 [============

2/2 [==============================] - 0s 7ms/step - loss: 13545067520.0000
Epoch 183/500
2/2 [==============================] - 0s 3ms/step - loss: 13542759424.0000
Epoch 184/500
2/2 [==============================] - 0s 4ms/step - loss: 13540408320.0000
Epoch 185/500
2/2 [==============================] - 0s 5ms/step - loss: 13538169856.0000
Epoch 186/500
2/2 [==============================] - 0s 3ms/step - loss: 13535447040.0000
Epoch 187/500
2/2 [==============================] - 0s 5ms/step - loss: 13532792832.0000
Epoch 188/500
2/2 [==============================] - 0s 4ms/step - loss: 13529936896.0000
Epoch 189/500
2/2 [==============================] - 0s 5ms/step - loss: 13526915072.0000
Epoch 190/500
2/2 [==============================] - 0s 4ms/step - loss: 13524261888.0000
Epoch 191/500
2/2 [==============================] - ETA: 0s - loss: 14047287296.000 - 0s 5ms/step - loss: 13521089536.0000
Epoch 192/500
2/2 [==============================] - 0s 4ms/step - loss: 1351788

2/2 [==============================] - 0s 4ms/step - loss: 12806733824.0000
Epoch 273/500
2/2 [==============================] - 0s 6ms/step - loss: 12788357120.0000
Epoch 274/500
2/2 [==============================] - 0s 4ms/step - loss: 12770768896.0000
Epoch 275/500
2/2 [==============================] - 0s 4ms/step - loss: 12751296512.0000
Epoch 276/500
2/2 [==============================] - 0s 5ms/step - loss: 12728605696.0000
Epoch 277/500
2/2 [==============================] - 0s 4ms/step - loss: 12706289664.0000
Epoch 278/500
2/2 [==============================] - 0s 4ms/step - loss: 12687102976.0000
Epoch 279/500
2/2 [==============================] - 0s 5ms/step - loss: 12668858368.0000
Epoch 280/500
2/2 [==============================] - 0s 4ms/step - loss: 12648395776.0000
Epoch 281/500
2/2 [==============================] - 0s 5ms/step - loss: 12624674816.0000
Epoch 282/500
2/2 [==============================] - 0s 4ms/step - loss: 12599759872.0000
Epoch 283/500
2/2 [=====

2/2 [==============================] - 0s 5ms/step - loss: 9254516736.0000
Epoch 363/500
2/2 [==============================] - 0s 4ms/step - loss: 9194764288.0000
Epoch 364/500
2/2 [==============================] - 0s 5ms/step - loss: 9127726080.0000
Epoch 365/500
2/2 [==============================] - 0s 4ms/step - loss: 9054271488.0000
Epoch 366/500
2/2 [==============================] - 0s 5ms/step - loss: 8987222016.0000
Epoch 367/500
2/2 [==============================] - 0s 5ms/step - loss: 8914180096.0000
Epoch 368/500
2/2 [==============================] - 0s 5ms/step - loss: 8848508928.0000
Epoch 369/500
2/2 [==============================] - 0s 5ms/step - loss: 8768419840.0000
Epoch 370/500
2/2 [==============================] - 0s 5ms/step - loss: 8698914816.0000
Epoch 371/500
2/2 [==============================] - 0s 5ms/step - loss: 8623438848.0000
Epoch 372/500
2/2 [==============================] - 0s 4ms/step - loss: 8546543104.0000
Epoch 373/500
2/2 [================

2/2 [==============================] - 0s 6ms/step - loss: 2423825408.0000
Epoch 454/500
2/2 [==============================] - 0s 5ms/step - loss: 2387726080.0000
Epoch 455/500
2/2 [==============================] - 0s 5ms/step - loss: 2343736832.0000
Epoch 456/500
2/2 [==============================] - 0s 5ms/step - loss: 2297980416.0000
Epoch 457/500
2/2 [==============================] - 0s 4ms/step - loss: 2250784256.0000
Epoch 458/500
2/2 [==============================] - 0s 5ms/step - loss: 2208253184.0000
Epoch 459/500
2/2 [==============================] - 0s 5ms/step - loss: 2169108224.0000
Epoch 460/500
2/2 [==============================] - 0s 4ms/step - loss: 2133151744.0000
Epoch 461/500
2/2 [==============================] - 0s 4ms/step - loss: 2099655040.0000
Epoch 462/500
2/2 [==============================] - 0s 5ms/step - loss: 2077823744.0000
Epoch 463/500
2/2 [==============================] - 0s 3ms/step - loss: 2056035584.0000
Epoch 464/500
2/2 [================

In [23]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

print('Coefficients: \n', regressor.coef_)

Coefficients: 
 [  -55.38960354  -388.19983694   409.31479306 35467.54842832
   849.43867423  4674.99091431]


In [24]:
ypred = reg.predict(x_test)
ypred

array([[ 90512.47 ],
       [ 45411.117],
       [ 97279.56 ],
       [ 53944.367],
       [165142.34 ],
       [113884.82 ],
       [ 29160.06 ],
       [ 55524.848],
       [ 96401.59 ],
       [138713.92 ]], dtype=float32)

In [25]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])