In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Convolution2D,MaxPooling2D,Flatten
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
train_datagen = ImageDataGenerator(rescale = 1./255, shear_range = 0.2, zoom_range = 0.2 , horizontal_flip = True)
test_datagen = ImageDataGenerator(rescale = 1./255)

In [3]:
x_train = train_datagen.flow_from_directory(r"E:\SmartInternz_Pynb\Image_for_ass6 data\trainset", target_size = (64,64), batch_size = 32, class_mode = "categorical")
x_test = test_datagen.flow_from_directory(r"E:\SmartInternz_Pynb\Image_for_ass6 data\testset", target_size = (64,64), batch_size = 32, class_mode = "categorical")

Found 100 images belonging to 10 classes.
Found 100 images belonging to 10 classes.


In [4]:
cnn = Sequential()

In [5]:
cnn.add(Convolution2D(32, (3, 3), input_shape= (64, 64, 3)))

In [6]:
cnn.add(MaxPooling2D((2,2)))

In [7]:
cnn.add(Flatten())

In [8]:
cnn.add(Dense(units = 100, kernel_initializer = "random_uniform", activation = "relu"))

In [9]:
cnn.add(Dense(units = 10, kernel_initializer = "random_uniform", activation = "softmax"))

In [10]:
cnn.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics = ["accuracy"])

In [11]:
cnn.fit_generator(x_train , steps_per_epoch = len(x_train) , epochs = 50, validation_data = x_test , validation_steps = len(x_test))

C:\Users\User\anaconda3\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


Epoch 1/50
4/4 [==============================] - 16s 5s/step - loss: 3.6186 - accuracy: 0.1300 - val_loss: 2.3161 - val_accuracy: 0.1400
Epoch 2/50
4/4 [==============================] - 12s 3s/step - loss: 2.4052 - accuracy: 0.1000 - val_loss: 2.1733 - val_accuracy: 0.2900
Epoch 3/50
4/4 [==============================] - 12s 4s/step - loss: 2.2156 - accuracy: 0.2000 - val_loss: 2.0433 - val_accuracy: 0.4000
Epoch 4/50
4/4 [==============================] - 12s 4s/step - loss: 2.1737 - accuracy: 0.2100 - val_loss: 1.9544 - val_accuracy: 0.3600
Epoch 5/50
4/4 [==============================] - 12s 4s/step - loss: 2.0836 - accuracy: 0.2400 - val_loss: 1.8947 - val_accuracy: 0.3600
Epoch 6/50
4/4 [==============================] - 10s 3s/step - loss: 1.9714 - accuracy: 0.3500 - val_loss: 1.8311 - val_accuracy: 0.3500
Epoch 7/50
4/4 [==============================] - 12s 3s/step - loss: 1.9559 - accuracy: 0.2900 - val_loss: 1.7841 - val_accuracy: 0.4700
Epoch 8/50
4/4 [==================

In [12]:
cnn.save("Image.h5")

In [13]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

In [14]:
mod=load_model("Image.h5")

In [15]:
img1 = image.load_img("cat1.jpg", target_size=(64,64))
img2 = image.load_img("elephant6.jpg", target_size=(64,64))
img3 = image.load_img("fish1.jpg", target_size=(64,64))
img4 = image.load_img("iguana1.jpg", target_size=(64,64))
img5 = image.load_img("lemur6.jpg", target_size=(64,64))

In [16]:
x1 = image.img_to_array(img1)
x2 = image.img_to_array(img2)
x3 = image.img_to_array(img3)
x4 = image.img_to_array(img4)
x5 = image.img_to_array(img5)

In [17]:
import numpy as np
x1 = np.expand_dims(x1, axis = 0)
x2 = np.expand_dims(x2, axis = 0)
x3 = np.expand_dims(x3, axis = 0)
x4 = np.expand_dims(x4, axis = 0)
x5 = np.expand_dims(x5, axis = 0)

In [18]:
cat = mod.predict(x1)
elephant = mod.predict(x2)
fish = mod.predict(x3)
iguana = mod.predict(x4)
lemur = mod.predict(x5)

In [19]:
cat[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [20]:
elephant[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [21]:
fish[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [22]:
iguana[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [23]:
lemur[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)

In [24]:
image = ["cat", "eagle", "eel", "elephant", "elk", "fish", "hen", "iguana", "lemur", "newt"]

In [25]:
cat = image[np.argmax(cat[0])]
cat

'cat'

In [26]:
elephant = image[np.argmax(elephant[0])]
elephant

'elephant'

In [27]:
fish = image[np.argmax(fish[0])]
fish

'fish'

In [28]:
iguana = image[np.argmax(iguana[0])]
iguana

'iguana'

In [29]:
lemur = image[np.argmax(lemur[0])]
lemur

'lemur'