In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Convolution2D,MaxPooling2D,Flatten
from tensorflow.keras.preprocessing.image import ImageDataGenerator

ImportError: cannot import name 'Categorical' from 'tensorflow.keras.models' (C:\Users\User\Anaconda3\lib\site-packages\keras\api\_v2\keras\models\__init__.py)

In [ ]:
train_datagen = ImageDataGenerator(rescale = 1./255, shear_range = 0.2, zoom_range = 0.2 , horizontal_flip = True)
test_datagen = ImageDataGenerator(rescale = 1./255)

In [ ]:
x_train = train_datagen.flow_from_directory(r"E:\SmartInternz_Pynb\Assignment_7\A7_CNN\Image_for_ass6 data\trainset", target_size=(
    64, 64), batch_size=16, class_mode="categorical")
x_test = test_datagen.flow_from_directory(r"E:\SmartInternz_Pynb\Assignment_7\A7_CNN\Image_for_ass6 data\testset", target_size=(
    64, 64), batch_size=16, class_mode="categorical")


Found 70 images belonging to 10 classes.
Found 30 images belonging to 10 classes.


In [ ]:
cnn = Sequential()

In [ ]:
cnn.add(Convolution2D(32, (3, 3), input_shape= (64, 64, 3)))

In [ ]:
cnn.add(MaxPooling2D((2,2)))

In [ ]:
cnn.add(Flatten())

In [ ]:
cnn.add(Dense(units = 120, kernel_initializer = "random_uniform", activation = "relu"))

In [ ]:
cnn.add(Dense(units = 10, kernel_initializer = "random_uniform", activation = "softmax"))

In [ ]:
cnn.compile(optimizer = "rmsprop", loss = "categorical_crossentropy", metrics = ["accuracy"])

In [ ]:
cnn.fit_generator(x_train , steps_per_epoch = 70/16, epochs = 20, validation_data = x_test , validation_steps = 30/16)

C:\Users\User\Anaconda3\lib\site-packages\keras\engine\training.py:1972: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  warnings.warn('`Model.fit_generator` is deprecated and '


In [ ]:
cnn.save("Image.h5")

In [ ]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

In [ ]:
mod=load_model("Image.h5")

In [ ]:
img1 = image.load_img(r"E:\SmartInternz_Pynb\Assignment_7\A7_CNN\upload\cat1.jpg", target_size=(64, 64))
img2 = image.load_img(r"E:\SmartInternz_Pynb\Assignment_7\A7_CNN\upload\elephant6.jpg", target_size=(64, 64))
img3 = image.load_img(r"E:\SmartInternz_Pynb\Assignment_7\A7_CNN\upload\fish1.jpg", target_size=(64,64))
img4 = image.load_img(r"E:\SmartInternz_Pynb\Assignment_7\A7_CNN\upload\iguana1.jpg", target_size=(64, 64))
img5 = image.load_img(r"E:\SmartInternz_Pynb\Assignment_7\A7_CNN\upload\lemur6.jpg", target_size=(64,64))


In [ ]:
x1 = image.img_to_array(img1)
x2 = image.img_to_array(img2)
x3 = image.img_to_array(img3)
x4 = image.img_to_array(img4)
x5 = image.img_to_array(img5)

In [ ]:
import numpy as np
x1 = np.expand_dims(x1, axis = 0)
x2 = np.expand_dims(x2, axis = 0)
x3 = np.expand_dims(x3, axis = 0)
x4 = np.expand_dims(x4, axis = 0)
x5 = np.expand_dims(x5, axis = 0)

In [ ]:
cat = mod.predict(x1)
elephant = mod.predict(x2)
fish = mod.predict(x3)
iguana = mod.predict(x4)
lemur = mod.predict(x5)

In [ ]:
cat[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
elephant[0]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [ ]:
fish[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

In [ ]:
iguana[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [ ]:
lemur[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)

In [ ]:
image = ["cat", "eagle", "eel", "elephant", "elk", "fish", "hen", "iguana", "lemur", "newt"]

In [ ]:
cat = image[np.argmax(cat[0])]
cat

'cat'

In [ ]:
elephant = image[np.argmax(elephant[0])]
elephant

'elephant'

In [ ]:
fish = image[np.argmax(fish[0])]
fish

'fish'

In [ ]:
iguana = image[np.argmax(iguana[0])]
iguana

'iguana'

In [ ]:
lemur = image[np.argmax(lemur[0])]
lemur

'lemur'